namespace KYNXA_Desktop.Services;

public static partial class UiText
{
    private static IReadOnlyDictionary<string, string> MemoryTranslations { get; } = new Dictionary<string, string>
    {
        ["KYNXA · 记忆管理"] = "KYNXA · Memory management",
        ["KYNXA  /  记忆管理"] = "KYNXA  /  Memory management",
        ["记忆管理"] = "Memory management",
        ["打开"] = "Open",
        ["聊天记忆"] = "Chat memory",
        ["工作记忆"] = "Project memory",
        ["全局记忆"] = "Global memory",
        ["记忆范围"] = "Memory scope",
        ["搜索记忆"] = "Search memories",
        ["刷新"] = "Refresh",
        ["新增记忆"] = "Add memory",
        ["编辑记忆"] = "Edit memory",
        ["类型"] = "Type",
        ["记忆类型"] = "Memory type",
        ["事实"] = "Fact",
        ["偏好"] = "Preference",
        ["决定"] = "Decision",
        ["内容"] = "Content",
        ["记忆内容"] = "Memory content",
        ["输入需要保留的记忆"] = "Enter a memory to keep",
        ["暂无已保存的聊天"] = "No saved chats",
        ["暂无工作"] = "No projects",
        ["内容不能为空。"] = "Content cannot be empty.",
        ["记忆内容不能超过 {0} 个字符。"] = "Memory content cannot exceed {0} characters.",
        ["内容包含无效字符。"] = "Content contains an invalid character.",
        ["请选择有效的记忆类型。"] = "Choose a valid memory type.",
        ["{0} / {1} 字符"] = "{0} / {1} characters",
        ["{0} 条记忆"] = "{0} memories",
        ["正在读取记忆…"] = "Loading memories…",
        ["发送消息后，即可管理这个聊天的记忆。"] = "Send a message to manage memory for this chat.",
        ["创建工作后，即可管理工作记忆。"] = "Create a project to manage its memory.",
        ["未能读取记忆，请刷新重试。"] = "Could not load memories. Refresh to retry.",
        ["没有匹配的记忆"] = "No matching memories",
        ["暂无记忆，点击新增记忆。"] = "No memories yet. Select Add memory.",
        ["暂停使用"] = "Inactive",
        ["来源不可用"] = "Source unavailable",
        ["来源已归档"] = "Source archived",
        ["正常使用"] = "Active",
        ["手动添加"] = "Manually added",
        ["用户消息"] = "User message",
        ["来源聊天"] = "Source chat",
        ["来源"] = "Source",
        ["保存后用于当前范围的上下文。"] = "After saving, used in context for this scope.",
        ["更新时间"] = "Updated",
        ["记忆已在其他位置更新。已刷新列表并保留你的编辑，请核对后再次保存。"] = "Memory was updated elsewhere. The list is refreshed and your edits are kept. Review before saving again.",
        ["记忆版本冲突，刷新失败。编辑内容已保留，请先刷新。"] = "Memory version conflict; refresh failed. Your edits are kept. Refresh before saving.",
        ["已保存，但列表刷新失败。请刷新，避免重复添加。"] = "Saved, but the list could not refresh. Refresh before adding again.",
        ["已删除，但列表刷新失败。请刷新。"] = "Deleted, but the list could not refresh. Please refresh.",
        ["暂时无法确认是否保存成功。请刷新检查列表，避免重复添加。"] = "Unable to confirm the save. Refresh and check the list before adding again.",
        ["这条记忆已被删除。编辑内容已保留，可复制后新增。"] = "This memory was deleted. Your edits are kept; copy them to a new memory if needed.",
        ["请检查记忆内容。"] = "Check the memory content.",
        ["记忆操作失败，请重试。"] = "Memory operation failed. Please retry.",
        ["当前网关不支持记忆管理，请结束旧网关后重新打开 KYNXA。"] = "The running gateway does not support memory management. Stop the old gateway, then reopen KYNXA.",
        ["工作已归档，共享记忆暂停用于聊天。"] = "This project is archived. Shared memory is not used in chats.",
        ["工作已归档，暂停共享"] = "Project archived; sharing paused",
        ["删除这条记忆？"] = "Delete this memory?",
        ["删除后，它将不再用于模型上下文。"] = "After deletion, this memory will no longer be used in model context.",
        ["放弃未保存的修改？"] = "Discard unsaved changes?",
        ["当前编辑尚未保存。"] = "Your current edits have not been saved.",
        ["放弃修改"] = "Discard changes",
        ["已归档"] = "Archived",
        ["请先完成记忆编辑，再更改数据存储位置。"] = "Finish editing memory before changing the data storage location.",
        ["正在保存聊天，请稍后打开记忆管理。"] = "Chats are being saved. Open memory management after saving finishes.",
        ["记忆接口返回了空响应。"] = "The memory API returned an empty or invalid response.",
        ["记忆接口返回 HTTP {0}。"] = "The memory API returned HTTP {0}.",
    };
}
