// Public publisher sources and registry versions were checked on 2026-10-03.
// Hosted services are provider-managed; their implementation cannot be version-pinned by this client.
const runtime = (name, description) => ({ name, type: 'runtime', required: true, description });
const environment = (name, description, required = true) => ({ name, type: 'environment', required, description });
const stdio = (id, name, args, options = {}) => ({ id, name, transport: 'stdio', command: 'npx', args,
  enabled: false, protocolVersion: '2025-11-25', disabledTools: [], startupTimeoutMs: 60000, ...options });
const hosted = (id, name, url, options = {}) => ({ id, name, transport: 'streamable-http', command: '', args: [], url,
  enabled: false, protocolVersion: '2025-11-25', disabledTools: [], startupTimeoutMs: 30000, ...options });
const npm = (name, version, entryPoint = name.split('/').at(-1)) => ({ registry: 'npm', name, version, entryPoint });
const pypi = (name, version) => ({ registry: 'pypi', name, version, entryPoint: name });
const node = runtime('Node.js and npm/npx', 'Use the Node.js runtime available to the gateway. First launch downloads the pinned package.');
const python = version => [runtime('uv/uvx', 'Install Astral uv so uvx is available to the gateway.'),
  runtime('Python', `Python ${version} or newer; uvx resolves an isolated package environment.`)];

export const curatedMcpPresets = [
  { id: 'playwright', name: 'Playwright', description: 'Official Microsoft browser automation in an isolated headless profile.',
    sourceUrl: 'https://github.com/microsoft/playwright-mcp', capabilities: ['browser'],
    package: npm('@playwright/mcp', '0.0.83', 'playwright-mcp'), license: 'Apache-2.0', publisher: 'vendor', network: 'local-and-remote',
    requirements: [node, runtime('Playwright browser', 'A compatible browser must be installed before browser tools can run.')],
    notes: ['A separate isolated profile does not reuse your signed-in browser.',
      'Browser settings can select msedge on Windows when Chrome is not installed; the Node/npm runtime is bundled with KYNXA.'],
    server: stdio('playwright', 'Playwright', ['-y', '@playwright/mcp@0.0.83', '--headless', '--isolated']) },
  { id: 'github', name: 'GitHub', description: 'Official hosted GitHub service. Requires a user-provided Bearer authorization environment variable.',
    sourceUrl: 'https://github.com/github/github-mcp-server', capabilities: ['github'],
    license: 'MIT', publisher: 'vendor', network: 'remote',
    requirements: [environment('KYNXA_GITHUB_AUTHORIZATION', 'The complete Authorization header value: Bearer followed by a GitHub token.')],
    notes: ['Hosted version is managed by GitHub. No account access is available until credentials are configured.'],
    server: hosted('github', 'GitHub', 'https://api.githubcopilot.com/mcp/', { headerEnv: { Authorization: 'KYNXA_GITHUB_AUTHORIZATION' } }) },
  { id: 'fetch', name: 'Fetch', description: 'Official MCP reference server for fetching public webpages as text or Markdown with paging.',
    sourceUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch', capabilities: ['web-fetch'],
    package: pypi('mcp-server-fetch', '2026.8.18'), license: 'MIT', publisher: 'reference', network: 'local-and-remote',
    requirements: python('3.10'), notes: ['Optional: built-in web.fetch already reads public webpages without Python.',
      'Downloads and webpage access use the network. The external process is not the terminal sandbox.'],
    server: stdio('fetch', 'Fetch', ['mcp-server-fetch==2026.8.18'], { command: 'uvx', startupTimeoutMs: 120000, env: { PYTHONIOENCODING: 'utf-8' } }) },
  { id: 'git', name: 'Git', description: 'Official MCP reference server for repository status, diffs and history; mutation tools start disabled.',
    sourceUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/git', capabilities: ['git-history'],
    package: pypi('mcp-server-git', '2026.8.18'), license: 'MIT', publisher: 'reference', network: 'local',
    requirements: [...python('3.10'), runtime('Git', 'Git must be available to the gateway.')],
    notes: ['Set --repository to the intended repository to restrict access. This preset does not provide another filesystem tool set.'],
    server: stdio('git', 'Git', ['mcp-server-git==2026.8.18'], { command: 'uvx', startupTimeoutMs: 120000, env: { PYTHONIOENCODING: 'utf-8' },
      disabledTools: ['git_add', 'git_commit', 'git_reset', 'git_create_branch', 'git_checkout'] }) },
  { id: 'context7', name: 'Context7', description: 'Upstash library documentation and code examples. Anonymous usage is limited; an API key is optional.',
    sourceUrl: 'https://github.com/upstash/context7', capabilities: ['library-documentation'],
    package: npm('@upstash/context7-mcp', '4.1.1'), license: 'MIT', publisher: 'vendor', network: 'local-and-remote',
    requirements: [node, environment('KYNXA_CONTEXT7_API_KEY', 'Optional key: map CONTEXT7_API_KEY to this host environment variable in the service editor.', false)],
    notes: ['Anonymous limits are controlled by Upstash. Optional credentials are not added to the default process environment.'],
    server: stdio('context7', 'Context7', ['-y', '@upstash/context7-mcp@4.1.1']) },
  { id: 'chrome-devtools', name: 'Chrome DevTools', description: 'Official Google browser debugging, performance and network diagnostics in an isolated headless profile.',
    sourceUrl: 'https://github.com/ChromeDevTools/chrome-devtools-mcp', capabilities: ['browser-debugging'],
    package: npm('chrome-devtools-mcp', '1.10.1'), license: 'Apache-2.0', publisher: 'vendor', network: 'local-and-remote',
    requirements: [node, runtime('Google Chrome', 'Install a current stable Chrome; no signed-in profile is connected automatically.')],
    notes: ['Usage statistics, update checks and remote CrUX lookups are disabled. Complements Playwright with diagnostics.'],
    server: stdio('chrome-devtools', 'Chrome DevTools', ['-y', 'chrome-devtools-mcp@1.10.1', '--headless', '--isolated',
      '--no-usage-statistics', '--no-performance-crux'], { env: { CHROME_DEVTOOLS_MCP_NO_UPDATE_CHECKS: '1' } }) },
  { id: 'exa', name: 'Exa Search', description: 'Official hosted public web search. Anonymous usage is rate-limited and requires no account key.',
    sourceUrl: 'https://github.com/exa-labs/exa-mcp-server', capabilities: ['web-search'],
    license: 'MIT', publisher: 'vendor', network: 'remote', requirements: [],
    notes: ['Hosted version and anonymous rate limits are managed by Exa. Authenticated agent research is not enabled by this preset.'],
    server: hosted('exa', 'Exa Search', 'https://mcp.exa.ai/mcp', { disabledTools: ['web_fetch_exa'] }) },
  { id: 'brave-search', name: 'Brave Search', description: 'Official Brave search for web, news, images and local places. Requires a Brave Search API key.',
    sourceUrl: 'https://github.com/brave/brave-search-mcp-server', capabilities: ['news-and-place-search'],
    package: npm('@brave/brave-search-mcp-server', '2.1.4'), license: 'MIT', publisher: 'vendor', network: 'local-and-remote',
    requirements: [node, environment('KYNXA_BRAVE_API_KEY', 'A Brave Search API subscription key; saved only as an environment-variable reference.')],
    notes: ['Account subscription limits apply. No authenticated search has been verified.'],
    server: stdio('brave-search', 'Brave Search', ['-y', '@brave/brave-search-mcp-server@2.1.4', '--transport', 'stdio'],
      { envRefs: { BRAVE_API_KEY: 'KYNXA_BRAVE_API_KEY' } }) },
  { id: 'dbhub', name: 'DBHub Read-only', description: 'Bytebase database schema and read-only SQL for PostgreSQL, MySQL, SQL Server and SQLite. Requires a read-only TOML configuration and DSN.',
    sourceUrl: 'https://github.com/bytebase/dbhub', capabilities: ['database-readonly'],
    package: npm('@bytebase/dbhub', '1.4.0'), license: 'MIT', publisher: 'vendor', network: 'local-and-remote',
    requirements: [node, environment('KYNXA_DBHUB_DSN', 'A database connection string for a least-privilege read-only database account.'),
      { name: 'dbhub-readonly.toml', type: 'configuration', required: true, description: 'Save the supplied template and replace the absolute-path placeholder in arguments. Keep readonly=true.' }],
    notes: ['DBHub 1.4.0 removed --readonly; this preset requires the explicit read-only tool configuration.',
      'Use a read-only database account. A privileged database role can perform effects through database functions.'],
    configurationTemplate: '[[sources]]\nid = "readonly"\ndsn = "${DSN}"\n\n[[tools]]\nname = "search_objects"\nsource = "readonly"\n\n[[tools]]\nname = "execute_sql"\nsource = "readonly"\nreadonly = true\nmax_rows = 100\n',
    server: stdio('dbhub', 'DBHub Read-only', ['-y', '@bytebase/dbhub@1.4.0', '--transport', 'stdio', '--config', '<absolute-path-to-dbhub-readonly.toml>'],
      { envRefs: { DSN: 'KYNXA_DBHUB_DSN' } }) },
  { id: 'markitdown', name: 'MarkItDown', description: 'Official Microsoft conversion of PDF, Office documents and other formats to Markdown. The MCP package is a preview release.',
    sourceUrl: 'https://github.com/microsoft/markitdown/tree/main/packages/markitdown-mcp', capabilities: ['document-conversion'],
    package: pypi('markitdown-mcp', '0.0.1a7'), license: 'MIT', publisher: 'vendor', network: 'local-and-remote',
    requirements: python('3.10'), notes: ['Preview package; conversion runs as an external process with host access. No additional LLM/OCR account is configured.'],
    server: stdio('markitdown', 'MarkItDown', ['markitdown-mcp==0.0.1a7'], { command: 'uvx', startupTimeoutMs: 120000, env: { PYTHONIOENCODING: 'utf-8' } }) },
  { id: 'windows-screenshot', name: 'Windows Screenshot', description: 'Community CursorTouch Windows-MCP limited to Screenshot and Snapshot. Requires Windows and Python 3.14.',
    sourceUrl: 'https://github.com/CursorTouch/Windows-MCP', capabilities: ['desktop-screenshot'],
    package: pypi('windows-mcp', '0.8.7'), license: 'MIT', publisher: 'community', network: 'local',
    requirements: [runtime('Windows desktop', 'Requires an interactive Windows session.'), ...python('3.14')],
    notes: ['Optional: built-in computer tools already provide native screenshot and desktop interaction without Python.',
      'This is a community project, not a Microsoft server. Only screenshot and UI snapshot tools are exposed.',
      'Host screenshots may contain private information; use only after explicit approval. Anonymous telemetry is disabled.'],
    server: stdio('windows-screenshot', 'Windows Screenshot', ['windows-mcp==0.8.7', 'serve', '--tools', 'Screenshot,Snapshot'],
      { command: 'uvx', startupTimeoutMs: 120000, env: { ANONYMIZED_TELEMETRY: 'false', WINDOWS_MCP_SCREENSHOT_SCALE: '0.5', PYTHONIOENCODING: 'utf-8' } }) }
];
