namespace KYNXA_Desktop.Services;

public static partial class UiText
{
    private static IReadOnlyDictionary<string, string> AgentTranslations { get; } = new Dictionary<string, string>
    {
        ["KYNXA · 工具与技能"] = "KYNXA · Tools and skills",
        ["KYNXA  /  工具与技能"] = "KYNXA  /  Tools and skills",
        ["工具与技能"] = "Tools and skills",
        ["MCP 服务"] = "MCP servers",
        ["技能"] = "Skills",
        ["可用工具"] = "Available tools",
        ["刷新列表"] = "Refresh lists",
        ["服务 ID"] = "Server ID",
        ["名称"] = "Name",
        ["程序"] = "Executable",
        ["参数（JSON 字符串数组）"] = "Arguments (JSON string array)",
        ["启用服务"] = "Enable server",
        ["保存服务"] = "Save server",
        ["删除服务"] = "Delete server",
        ["新增服务"] = "Add server",
        ["用户技能目录"] = "User skill directories",
        ["添加目录"] = "Add directory",
        ["移除目录"] = "Remove directory",
        ["保存目录"] = "Save directories",
        ["选择技能以预览内容"] = "Select a skill to preview its content",
        ["选择工具以查看参数"] = "Select a tool to inspect its parameters",
        ["连接并刷新 MCP"] = "Connect and refresh MCP",
        ["连接会启动已启用的服务程序。"] = "Connecting starts enabled server programs.",
        ["启用的 MCP 服务会在模型请求或手动连接时启动。请核对程序和参数。"] = "Enabled MCP servers start on model requests or manual connection. Review the program and arguments.",
        ["技能作为模型参考。预览不会执行其中的脚本。"] = "Skills provide model guidance. Previewing does not run their scripts.",
        ["工具配置版本不受支持。"] = "This tool configuration version is unsupported.",
        ["工具列表读取失败，请重试。"] = "Could not load tools. Try again.",
        ["工具配置已保存。"] = "Tool configuration saved.",
        ["请先完成工具配置，再更改数据存储位置。"] = "Finish editing tool configuration before changing the data storage location.",
        ["配置已更新。编辑已保留，请核对列表后再次保存。"] = "Configuration changed. Your edits are preserved. Review the list before saving again.",
        ["配置冲突且刷新失败，请先刷新列表。"] = "Configuration conflict; reload failed. Refresh the list first.",
        ["工具配置保存失败。"] = "Could not save tool configuration.",
        ["MCP 服务已连接。"] = "MCP servers connected.",
        ["部分 MCP 服务连接失败，已保留可用工具。"] = "Some MCP servers could not connect. Available tools are retained.",
        ["MCP 连接失败，请核对程序和参数。"] = "MCP connection failed. Review the program and arguments.",
        ["请填写服务信息，并提供有效的 JSON 字符串数组参数。"] = "Complete the server fields and provide a valid JSON array of string arguments.",
        ["删除服务？"] = "Delete this server?",
        ["删除后，此服务不再连接。"] = "This server will no longer connect.",
        ["技能预览读取失败。"] = "Could not load the skill preview.",
        ["工具接口返回了无效的审批响应。"] = "The tool API returned an invalid approval response.",
        ["工具接口返回了空响应。"] = "The tool API returned an empty response.",
        ["工具接口返回 HTTP {0}。"] = "The tool API returned HTTP {0}.",
        ["工具审批缺少请求标识。"] = "The approval request is missing its identity.",
        ["工具事件无效。"] = "Invalid tool event.",
        ["读取挂载目录；修改、终端及外部工具需批准"] = "Read mounted folders; changes, terminal commands and external tools require approval",
        ["自动处理挂载内可逆操作；删除及外部访问需批准"] = "Automatically handle reversible operations in mounted folders; deletion and external access require approval",
        ["可访问系统允许的文件；优先挂载目录，终端仍受沙箱限制"] = "Access files allowed by the system, prefer mounted folders; terminal commands remain sandboxed",
        ["批准这次工具操作？"] = "Approve this tool operation?",
        ["批准一次"] = "Approve once",
        ["拒绝"] = "Deny",
        ["工作范围"] = "Workspace scope",
        ["范围未提供"] = "Scope not provided",
        ["此操作超出工作目录。"] = "This operation is outside the workspace.",
        ["此操作位于工作目录内。"] = "This operation is within the workspace.",
        ["此工具未提供本地文件范围。"] = "This tool did not provide a local file scope.",
        ["沙箱"] = "Sandbox",
        ["沙箱信息未提供"] = "Sandbox information not provided",
        ["工具活动"] = "Tool activity",
        ["执行中"] = "Running",
        ["已完成"] = "Completed",
        ["工具失败"] = "Tool failed",
        ["已拒绝"] = "Denied",
        ["等待批准"] = "Awaiting approval"
    };
}
