<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ColorCode.Core" Version="2.0.15" />
    <Compile Include="../../apps/desktop/Services/Presentation/CodeSyntaxHighlighter.cs" Link="CodeSyntaxHighlighter.cs" />
  </ItemGroup>
</Project>
